<template>
  <div>
    <v-form>
      <v-text-field
        :rules="(
          $validate('email')
            .required()
            .email()
            .getRules()
        )"
      />
    </v-form>
  </div>
</template>
